---
:audiences_preferences:
  :children:
    :cartoon: 1
  :teenagers:
    :action: 0.25
    :scify: 0.25
    :comedy: 0.25
    :terror: 0.25
  :adult:
    :action: 0.2
    :scify: 0.2
    :comedy: 0.1
    :drama: 0.1
    :terror: 0.05
    :nature: 0.1
    :history: 0.05
    :society: 0.05
    :technology: 0.15
  :elderly:
    :action: 0.1
    :scify: 0.1
    :comedy: 0.25
    :drama: 0.2
    :nature: 0.2
    :history: 0.1
    :society: 0.05

:times:
  0:
    :children: 0.25
    :teenagers: 0.25
    :adult: 0.25
    :elderly: 0.25
  1:
    :children: 0.25
    :teenagers: 0.25
    :adult: 0.25
    :elderly: 0.25
  2:
    :children: 0.25
    :teenagers: 0.25
    :adult: 0.25
    :elderly: 0.25
  3:
    :children: 0.25
    :teenagers: 0.25
    :adult: 0.25
    :elderly: 0.25
  4:
    :children: 0.25
    :teenagers: 0.25
    :adult: 0.25
    :elderly: 0.25
  5:
    :children: 0.25
    :teenagers: 0.25
    :adult: 0.25
    :elderly: 0.25
  6:
    :children: 0.25
    :teenagers: 0.25
    :adult: 0.25
    :elderly: 0.25
  7:
    :children: 0.25
    :teenagers: 0.25
    :adult: 0.25
    :elderly: 0.25
  8:
    :children: 0.25
    :teenagers: 0.25
    :adult: 0.25
    :elderly: 0.25
  9:
    :children: 0.25
    :teenagers: 0.25
    :adult: 0.25
    :elderly: 0.25
  10:
    :children: 0.25
    :teenagers: 0.25
    :adult: 0.25
    :elderly: 0.25
  11:
    :children: 0.25
    :teenagers: 0.25
    :adult: 0.25
    :elderly: 0.25
