development:
  adapter: postgresql
  encoding: unicode
  database: spinoff_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: spinoff_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: spinoff_production
  pool: 5
